name: Despliegue Parroquia San Patricio

on:
  push:
    branches:
      - main  # Asegúrate de que tu rama se llame main

jobs:
  web-deploy:
    name: 🎉 Deploy a Hostinger
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obtener código desde GitHub
      uses: actions/checkout@v4

    - name: 📂 Sincronizar archivos vía FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Apunta exactamente a la carpeta web pública de Hostinger
        server-dir: public_html/ 
        # Si quieres que borre archivos en el servidor que ya no están en GitHub, cambia a true
        delete-destination-after-sync: false