name: Despliegue Parroquia San Patricio

# El proceso se activa cada vez que haces un 'git push'
on:
  push:
    branches:
      - main  # Verifica que tu rama principal se llame 'main'

jobs:
  web-deploy:
    name: 🎉 Deploy a Hostinger
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Obtener código desde GitHub
      uses: actions/checkout@v4

    - name: 📂 Sincronizar archivos vía FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        # Estos datos se sacan de Settings > Secrets > Actions
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        
        # IMPORTANTE: Usamos './' porque el usuario FTP de Hostinger 
        # ya está configurado para entrar directo a 'public_html'
        server-dir: ./ 
        
        # Aumentamos el tiempo límite por si la FTP de Hostinger demora en responder
        timeout: 300000